version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: arbitrum_blocks
      - name: arbitrum_txs
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
      - name: ez_hourly_prices
      - name: dim_labels
      - name: ez_hourly_token_prices
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
      - name: ez_hourly_token_prices
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "ARBITRUM_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "ARBITRUM" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceBlockByNumber
      - name: decoded_logs
      - name: confirm_blocks
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables:
      - name: node_mapping
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: apis_keys
      - name: address_labels
      - name: token_prices_priority_hourly
      - name: asset_metadata_priority
      - name: number_sequence
      - name: token_prices_all_providers_hourly
      - name: asset_metadata_all_providers
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: arbitrum_silver
    database: arbitrum
    schema: silver
    tables:
      - name: verified_abis
  - name: arbitrum_bronze_api
    database: arbitrum
    schema: bronze_api
    tables:
      - name: contract_abis
