version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: arbitrum_blocks
      - name: arbitrum_txs
  - name: crosschain
    database: crosschain
    schema: silver
    tables:
      - name: address_labels   
  - name: ethereum 
    database: ethereum
    schema: core 
    tables: 
      - name: fact_hourly_token_prices
  - name: symbols_cross_tab
    database: FLIPSIDE_PROD_DB
    schema: SILVER
    tables:
      - name: MARKET_ASSET_METADATA
  - name: arbitrum_pools
    database: arbitrum
    schema: bronze
    tables:
      - name: SUSHI_DIM_DEX_POOLS
      - name: SUSHI_DIM_KASHI_POOLS
  - name: prices
    database: FLIPSIDE_PROD_DB
    schema: SILVER
    tables:
      - name: prices_v2
  - name: bronze_api
    database: arbitrum
    schema: bronze_api
    tables:
      - name: contract_abis
      - name: token_reads