version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'ARBITRUM' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ var('GLOBAL_PROD_DB_NAME') ~ ('_dev' if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else '') }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceblockbynumber
      - name: decoded_logs
      - name: confirm_blocks
      - name: blocks_v2
      - name: transactions_v2
      - name: receipts_v2
      - name: traces_v2
      - name: confirm_blocks_v2
      - name: decoded_logs_v2
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: address_labels
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: arbitrum_silver
    database: arbitrum
    schema: silver
    tables:
      - name: verified_abis
      - name: traces
  - name: arbitrum_bronze_api
    database: arbitrum
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: arbitrum
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
  - name: arbitrum_gold
    database: "{{ 'arbitrum' if target.database == 'ARBITRUM' else 'arbitrum_dev' }}"
    schema: core
    tables:
      - name: fact_traces
